 <link rel="stylesheet" type="text/css" href="css/navigation.css">

 <nav class="itemnav menu">  
      <ul>
        <li><a href="index.php">Home</a></li>
        <li><a href="fiyin.php">Fiyinfoluwa Oluyinka</a></li>
        <li><a href="olatunde.php"> Olatunde Oshunlaja </a></li>
        <li><a href="prosper.php">Prosper Feya</a></li>
        <li><a href="sarah.php">Sarah</a></li>
        <li><a href="submit.php">Submit Product Proposal</a></li>
      </ul>
 </nav>